spring.config.import=optional:file:${user.dir}/application-secret.properties

server.port=8086
spring.application.name=auth-service

spring.docker.compose.enabled=false

spring.data.redis.host=${AUTH_REDIS_HOST}
spring.data.redis.port=${AUTH_REDIS_PORT}
spring.data.redis.password=${AUTH_REDIS_PASSWORD}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=auth-service
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=30
eureka.instance.lease-expiration-duration-in-seconds=90

jwt.secret=${JWT_SECRET}
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY}
jwt.refresh-token-validity=${JWT_REFRESH_TOKEN_VALIDITY}

spring.main.allow-bean-definition-overriding=true
