spring.config.import=optional:file:${user.dir}/application-secret.properties

server.port=0
spring.application.name=sample-service

spring.docker.compose.enabled=false

spring.datasource.url=${SAMPLE_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${SAMPLE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

management.tracing.zipkin.endpoint=${ZIPKIN_ENDPOINT}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
