server:
  port: 8085 # 알림 서비스용 포트

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tenten_notification
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# 슬랙 설정
slack:
  # 환경 변수 SLACK_BOT_TOKEN 값을 읽어오고, 없으면 빈 문자열 사용
  token: ${SLACK_BOT_TOKEN:}
  # 환경 변수 SLACK_WEBHOOK_URL 값을 읽어옴
  webhook-url: ${SLACK_WEBHOOK_URL:}