addReviewers: true

addAssignees: author

reviewers:
  - ji-circle
  - gelong25
  - M1Nj1M
  - No-366
  - rlaxxwls13

numberOfReviewers: 5

numberOfAssignees: 1

# 'wip' 키워드가 제목에 있으면 실행 안 함
skipKeywords:
  - wip