spring.config.import=optional:file:${user.dir}/application-common.properties,optional:file:${user.dir}/application-secret.properties
# ----------------------------------------
# Application
# ----------------------------------------
server.port=8000
spring.application.name=api-gateway
# ----------------------------------------
# Gateway Routes
# ----------------------------------------
# sample
spring.cloud.gateway.server.webmvc.routes[0].id=sample-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://sample-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/main/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/main(?<segment>.*), /api/v1/main$\{segment}
# company
spring.cloud.gateway.server.webmvc.routes[1].id=company-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://company-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/companies/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=RewritePath=/companies(?<segment>.*), /api/v1/companies$\{segment}
# delivery
spring.cloud.gateway.server.webmvc.routes[2].id=delivery-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://delivery-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/deliveries/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=RewritePath=/deliveries(?<segment>.*), /api/v1/deliveries$\{segment}
# notification
spring.cloud.gateway.server.webmvc.routes[3].id=notification-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://notification-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/notifications/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=RewritePath=/notifications(?<segment>.*), /api/v1/notifications$\{segment}
# auth
spring.cloud.gateway.server.webmvc.routes[4].id=auth-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=RewritePath=/auth(?<segment>.*), /api/v1/auth$\{segment}
# user
spring.cloud.gateway.server.webmvc.routes[5].id=user-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=RewritePath=/users(?<segment>.*), /api/v1/users$\{segment}
# hub
spring.cloud.gateway.server.webmvc.routes[6].id=hub-server
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://hub-service
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/hubs/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=RewritePath=/hubs(?<segment>.*), /api/v1/hubs$\{segment}
# product
spring.cloud.gateway.server.webmvc.routes[7].id=product-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://product-service
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=RewritePath=/products(?<segment>.*), /api/v1/products$\{segment}
# ai
spring.cloud.gateway.server.webmvc.routes[8].id=ai-analysis
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ai-service
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/ais/analysis
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=AddRequestHeader=X-Internal-Request, true
spring.cloud.gateway.server.webmvc.routes[8].filters[1]=RewritePath=/ais(?<segment>.*), /internal/v1/ais$\{segment}
spring.cloud.gateway.server.webmvc.routes[9].id=ai-api
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ai-service
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/ais/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=RewritePath=/ais(?<segment>.*), /api/v1/ais$\{segment}
# ----------------------------------------
# Eureka
# ----------------------------------------
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.registry-fetch-interval-seconds=5
# ----------------------------------------
# Logging
# ----------------------------------------
logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=DEBUG
# ----------------------------------------
# JWT
# ----------------------------------------
jwt.secret=${JWT_SECRET:test-secret-key-test-secret-key-test-secret-key}
jwt.access-token-validity=${JWT_ACCESS_TOKEN_VALIDITY:1h}
jwt.refresh-token-validity=${JWT_REFRESH_TOKEN_VALIDITY:7d}
# ----------------------------------------
# Redis
# ----------------------------------------
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD:}
# ----------------------------------------
# zipkin
# ----------------------------------------
management.tracing.enabled=true
management.zipkin.tracing.export.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}
