spring.config.import=optional:file:${user.dir}/application-common.properties,optional:file:${user.dir}/application-secret.properties
spring.application.name=ai-service
server.port=8088
spring.datasource.url=${AI_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# zipkin
management.tracing.enabled=true
management.zipkin.tracing.export.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0
# Hibernate JSON ?? ?? ???
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
app.delivery.notification-time=06:00
spring.cloud.stream.bindings.ai-notification-out-0.destination=ai-notification-topic
spring.cloud.stream.kafka.binder.brokers=${KAFKA_BOOTSTRAP_SERVERS}
spring.cloud.stream.bindings.ai-notification-out-0.content-type=application/json
# Naver API
naver.api.client-key=${NAVER_API_CLIENT_KEY}
naver.api.client-secret=${NAVER_API_CLIENT_SECRET}
