server:
    port: 10101

spring:
    application:
        name: user-service

    docker:
        compose:
            enabled: false

    datasource:
        url: jdbc:postgresql://localhost:5432/user_db
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate

    flyway:
        baseline-on-migrate: true
        baseline-version: 0

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        register-with-eureka: true
        fetch-registry: true
    instance:
        hostname: user-service
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90
