spring.config.import=optional:file:${user.dir}/application-secret.properties

server.port=8090
spring.application.name=hub-server

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${HUB_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}

spring.flyway.enabled=false

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.instance.prefer-ip-address=true
