spring.config.import=optional:file:${user.dir}/application-common.properties,optional:file:${user.dir}/application-secret.properties
spring.application.name=product-service
server.port=8083
spring.datasource.url=${PRODUCT_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
management.tracing.enabled=true
management.zipkin.tracing.export.enabled=true
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}
